# Generated by Django 3.0.7 on 2020-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
