# Generated by Django 3.0.7 on 2020-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_posts_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
