# Generated by Django 3.1 on 2020-08-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200817_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
