# Generated by Django 3.1 on 2020-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200817_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Blog_title_tag',
            field=models.CharField(default='The Blog Title Tag', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_title_tag',
            field=models.CharField(default='The Project Title Tag', max_length=200),
        ),
    ]
